/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package GUI_QuanLy;

import BUS.BUS_KhuyenMai;
import DAL.DAL_KhuyenMai;
import DTO.DTO_KhuyenMai;
import QLController.QuanLyKhuyenMaiController;
import java.io.FileOutputStream;
import java.io.IOException;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
import org.apache.poi.ss.usermodel.Cell;
import org.apache.poi.ss.usermodel.CellType;
import org.apache.poi.xssf.usermodel.XSSFRow;
import org.apache.poi.xssf.usermodel.XSSFSheet;
import org.apache.poi.xssf.usermodel.XSSFWorkbook;

/**
 *
 * @author Admin
 */
public class GUI_QuanLyKhuyenMai extends javax.swing.JPanel {

    /**
     * Creates new form GUI_QuanLyKhuyenMai
     */
    String date;
    DateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
    private BUS_KhuyenMai kmbus=new BUS_KhuyenMai();
    private QuanLyKhuyenMaiController controller;
    public GUI_QuanLyKhuyenMai() {
        initComponents();
        controller=new QuanLyKhuyenMaiController(jpnView, btnThem2, jtfTim1, this);
        controller.setDateToTable();
        controller.setEvent();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        QuanLyKhuyenMai = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jtfTim1 = new javax.swing.JTextField();
        jPanel7 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        btnThem2 = new javax.swing.JButton();
        btnNhapFile = new javax.swing.JButton();
        bntXuat = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jpnView = new javax.swing.JPanel();

        setLayout(new java.awt.BorderLayout());

        QuanLyKhuyenMai.setLayout(new java.awt.BorderLayout());

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));
        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Tìm kiếm", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14))); // NOI18N
        jPanel6.setPreferredSize(new java.awt.Dimension(1432, 70));
        jPanel6.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        jtfTim1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jtfTim1.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 1, 1, 0, new java.awt.Color(204, 204, 204)));
        jtfTim1.setPreferredSize(new java.awt.Dimension(250, 30));
        jPanel6.add(jtfTim1);

        QuanLyKhuyenMai.add(jPanel6, java.awt.BorderLayout.PAGE_START);

        jPanel7.setBackground(new java.awt.Color(17, 153, 142));
        jPanel7.setPreferredSize(new java.awt.Dimension(1432, 20));

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1432, Short.MAX_VALUE)
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );

        QuanLyKhuyenMai.add(jPanel7, java.awt.BorderLayout.PAGE_END);

        jPanel8.setBackground(new java.awt.Color(17, 153, 142));
        jPanel8.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Chức năng", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14))); // NOI18N
        jPanel8.setPreferredSize(new java.awt.Dimension(230, 529));
        jPanel8.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 5, 15));

        btnThem2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnThem2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/themKieu1.png"))); // NOI18N
        btnThem2.setText("THÊM");
        btnThem2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnThem2.setPreferredSize(new java.awt.Dimension(150, 50));
        btnThem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThem2ActionPerformed(evt);
            }
        });
        jPanel8.add(btnThem2);

        btnNhapFile.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnNhapFile.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/addFile.png"))); // NOI18N
        btnNhapFile.setText("NHẬP FILE");
        btnNhapFile.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnNhapFile.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnNhapFile.setPreferredSize(new java.awt.Dimension(150, 50));
        btnNhapFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNhapFileActionPerformed(evt);
            }
        });
        jPanel8.add(btnNhapFile);

        bntXuat.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        bntXuat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/xuatFile.png"))); // NOI18N
        bntXuat.setText("XUẤT FILE");
        bntXuat.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        bntXuat.setPreferredSize(new java.awt.Dimension(150, 50));
        bntXuat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntXuatActionPerformed(evt);
            }
        });
        jPanel8.add(bntXuat);

        QuanLyKhuyenMai.add(jPanel8, java.awt.BorderLayout.LINE_END);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Danh sách khuyến mãi", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14))); // NOI18N

        javax.swing.GroupLayout jpnViewLayout = new javax.swing.GroupLayout(jpnView);
        jpnView.setLayout(jpnViewLayout);
        jpnViewLayout.setHorizontalGroup(
            jpnViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1180, Short.MAX_VALUE)
        );
        jpnViewLayout.setVerticalGroup(
            jpnViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 634, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jpnView, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jpnView, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        QuanLyKhuyenMai.add(jPanel2, java.awt.BorderLayout.CENTER);

        add(QuanLyKhuyenMai, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void btnThem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThem2ActionPerformed

    }//GEN-LAST:event_btnThem2ActionPerformed

    private void bntXuatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntXuatActionPerformed
        try{    
                    System.out.println("xuat");
                    XSSFWorkbook workbook =new XSSFWorkbook();
                    XSSFSheet sheet =workbook.createSheet("Sản phẩm");
                    XSSFRow headerRow = sheet.createRow(0);
                    XSSFRow row=null;
                    Cell cell=null;
                    
                    cell=headerRow.createCell(0,CellType.STRING);
                    cell.setCellValue("STT");
                    cell=headerRow.createCell(1,CellType.STRING);
                    cell.setCellValue("Mã khuyến mãi");
                    cell=headerRow.createCell(2,CellType.STRING);
                    cell.setCellValue("Mã sản phẩm");
                    cell=headerRow.createCell(3,CellType.STRING);
                    cell.setCellValue("Tên sản phẩm");
                    cell=headerRow.createCell(4,CellType.STRING);
                    cell.setCellValue("Tên Khuyến mãi");
                    cell=headerRow.createCell(5,CellType.STRING);
                    cell.setCellValue("Phần trăm khuyến mãi");
                    cell=headerRow.createCell(6,CellType.NUMERIC);
                    cell.setCellValue("Ngày bắt đầu");
                    cell=headerRow.createCell(7,CellType.STRING);
                    cell.setCellValue("Ngày kết thúc");
//                    row =sheet.createRow(7);
                    DAL_KhuyenMai sanPhamService = new DAL_KhuyenMai();
                    List<DTO_KhuyenMai> listItem= sanPhamService.getList();
                    List<DTO_KhuyenMai> listItem1=new ArrayList<>();
                    for (int i=0;i<listItem.size();i++){
                        if(listItem.get(i).getTRANGTHAI()==1)
                            listItem1.add(listItem.get(i));
                    }
                    Date d= new Date(System.currentTimeMillis());
        
                    date = dateFormat.format(d);
                    if (listItem1 != null){
                        int s=listItem1.size();
                        int dem=0;
                        for (int i=0;i<s;i++){
                            DTO_KhuyenMai km=  listItem1.get(i);
                            String date1=dateFormat.format(km.getNGAYKT());
                            if(date.compareTo(date1)<=0){
                            row =sheet.createRow(dem+1);
                            dem++;
                            cell=row.createCell(0,CellType.NUMERIC);
                            cell.setCellValue(dem);
                            cell=row.createCell(1,CellType.STRING);
                            cell.setCellValue(km.getMAKM());
                            cell=row.createCell(2,CellType.STRING);
                            cell.setCellValue(km.getMASP());
                            cell=row.createCell(3,CellType.STRING);
                            cell.setCellValue(km.getTENSP());
                            cell=row.createCell(4,CellType.STRING);
                            cell.setCellValue(km.getTENKM());
                            cell=row.createCell(5,CellType.NUMERIC);
                            cell.setCellValue(km.getPHANTRAMKM());
                            cell=row.createCell(6,CellType.STRING);
                            cell.setCellValue(km.getNGAYBD().toString());
                            cell=row.createCell(7,CellType.STRING);
                            cell.setCellValue(km.getNGAYKT().toString());
                            
                            }
                        }

                       JFileChooser fileChooser = new JFileChooser();
                        FileNameExtensionFilter filter = new FileNameExtensionFilter("File Excel", "xlsx");
                        fileChooser.setFileFilter(filter);

                        int returnValue = fileChooser.showSaveDialog(null);
                        if (returnValue == JFileChooser.APPROVE_OPTION) {
                            String filePath = fileChooser.getSelectedFile().getAbsolutePath();

                            // Đảm bảo đuôi file .xlsx
                            if (!filePath.endsWith(".xlsx")) {
                                filePath += ".xlsx";
                            }

                            // Lưu workbook ra file theo đường dẫn và tên file của người dùng đã chọn
                            FileOutputStream fileOut;
                            try {
                                fileOut = new FileOutputStream(filePath);
                                workbook.write(fileOut);
                                fileOut.close();
                                workbook.close();
                                JOptionPane.showMessageDialog(null, "Xuất thành công", "Thông báo", JOptionPane.WARNING_MESSAGE);
                            } catch (IOException e) {
                                e.printStackTrace();
                            }
                        } 
                    }
                    

                }catch (Exception h){
                    h.printStackTrace();
                    JOptionPane.showMessageDialog(null, "Xuất thất bại", "Thông báo", JOptionPane.WARNING_MESSAGE);
                }
    }//GEN-LAST:event_bntXuatActionPerformed

    private void btnNhapFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNhapFileActionPerformed
        kmbus.ThemDS();
        controller.setDateToTable();
        
    }//GEN-LAST:event_btnNhapFileActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel QuanLyKhuyenMai;
    private javax.swing.JButton bntXuat;
    private javax.swing.JButton btnNhapFile;
    private javax.swing.JButton btnThem2;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jpnView;
    private javax.swing.JTextField jtfTim1;
    // End of variables declaration//GEN-END:variables
}
