/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI_QuanLy;

import BUS.BUS_TaiKhoan;
import DTO.DTO_TaiKhoan;
import QLController.QuanLyTaiKhoanController;
import function.funcDungChung;
import javax.swing.JOptionPane;

/**
 *
 * @author Admin
 */
public class GUI_ThongTinTaiKhoan extends javax.swing.JFrame {

    /**
     * Creates new form GUI_ThongTinTaiKhoan2
     */
    private QuanLyTaiKhoanController ql;
    private BUS_TaiKhoan tkbus = new BUS_TaiKhoan();
    private DTO_TaiKhoan taikhoan = new DTO_TaiKhoan();
    private funcDungChung f =new funcDungChung();
    private boolean event = false;
    
    
    public GUI_ThongTinTaiKhoan(DTO_TaiKhoan taikhoan,QuanLyTaiKhoanController ql) {
        initComponents();
        this.setLocationRelativeTo(null);
        jtfMANV.setText(taikhoan.getMANV());
        jtfTK.setText(taikhoan.getTENDN());
        jtfMK.setText(taikhoan.getMK());
//        jcbPQ.addItem("Admin");
//        jcbPQ.addItem("Quản lý");
//        jcbPQ.addItem("Nhân viên");
        if(taikhoan.getPQ().equals("ql"))
            jcbPQ.setSelectedIndex(1);
        else if(taikhoan.getPQ().equals("nv"))
            jcbPQ.setSelectedIndex(2);
        
        this.ql=ql;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jtfTK = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jtfMK = new javax.swing.JTextField();
        jtfMANV = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jcbPQ = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        lbMk = new javax.swing.JLabel();
        kGradientPanel1 = new keeptoo.KGradientPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        btnLuu = new javax.swing.JButton();
        btnSua = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(526, 468));

        jPanel1.setPreferredSize(new java.awt.Dimension(526, 441));
        jPanel1.setLayout(new java.awt.BorderLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new java.awt.BorderLayout());

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Thông tin tài khoản", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14))); // NOI18N
        jPanel3.setOpaque(false);

        jPanel4.setOpaque(false);
        jPanel4.setPreferredSize(new java.awt.Dimension(500, 300));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Tài khoản :");
        jPanel4.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 96, -1, -1));

        jtfTK.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jtfTK.setEnabled(false);
        jtfTK.setPreferredSize(new java.awt.Dimension(250, 30));
        jPanel4.add(jtfTK, new org.netbeans.lib.awtextra.AbsoluteConstraints(185, 90, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Mã nhân viên :");
        jPanel4.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(48, 27, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Mật khẩu :");
        jPanel4.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(73, 160, -1, -1));

        jtfMK.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jtfMK.setEnabled(false);
        jtfMK.setPreferredSize(new java.awt.Dimension(250, 30));
        jPanel4.add(jtfMK, new org.netbeans.lib.awtextra.AbsoluteConstraints(185, 154, -1, -1));

        jtfMANV.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jtfMANV.setEnabled(false);
        jtfMANV.setPreferredSize(new java.awt.Dimension(250, 30));
        jPanel4.add(jtfMANV, new org.netbeans.lib.awtextra.AbsoluteConstraints(185, 27, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Chức vụ :");
        jPanel4.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(76, 222, -1, -1));

        jcbPQ.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Admin", "Quản lý", "Nhân viên" }));
        jcbPQ.setEnabled(false);
        jcbPQ.setPreferredSize(new java.awt.Dimension(72, 30));
        jPanel4.add(jcbPQ, new org.netbeans.lib.awtextra.AbsoluteConstraints(185, 216, 85, -1));
        jPanel4.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(185, 126, 250, 16));

        lbMk.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lbMk.setForeground(new java.awt.Color(255, 0, 0));
        jPanel4.add(lbMk, new org.netbeans.lib.awtextra.AbsoluteConstraints(75, 190, 360, -1));

        jPanel3.add(jPanel4);

        jPanel2.add(jPanel3, java.awt.BorderLayout.CENTER);

        kGradientPanel1.setkEndColor(new java.awt.Color(17, 153, 142));
        kGradientPanel1.setkStartColor(new java.awt.Color(17, 153, 142));
        kGradientPanel1.setPreferredSize(new java.awt.Dimension(600, 70));
        kGradientPanel1.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("TÀI KHOẢN");
        jLabel7.setPreferredSize(new java.awt.Dimension(430, 60));
        kGradientPanel1.add(jLabel7);

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/cross32.png"))); // NOI18N
        jLabel8.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel8MouseClicked(evt);
            }
        });
        kGradientPanel1.add(jLabel8);

        jPanel2.add(kGradientPanel1, java.awt.BorderLayout.PAGE_START);

        jPanel5.setBackground(new java.awt.Color(17, 153, 142));
        jPanel5.setPreferredSize(new java.awt.Dimension(600, 70));
        jPanel5.setLayout(new java.awt.BorderLayout());

        jPanel6.setOpaque(false);
        jPanel6.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 15, 15));

        btnLuu.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnLuu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/luuFile.png"))); // NOI18N
        btnLuu.setText("Lưu");
        btnLuu.setPreferredSize(new java.awt.Dimension(110, 40));
        btnLuu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLuuActionPerformed(evt);
            }
        });
        jPanel6.add(btnLuu);

        btnSua.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnSua.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/chinhSuaNhanVien2.png"))); // NOI18N
        btnSua.setText("Sửa Quyền");
        btnSua.setPreferredSize(new java.awt.Dimension(145, 40));
        btnSua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaActionPerformed(evt);
            }
        });
        jPanel6.add(btnSua);

        jPanel5.add(jPanel6, java.awt.BorderLayout.CENTER);

        jPanel2.add(jPanel5, java.awt.BorderLayout.PAGE_END);

        jPanel1.add(jPanel2, java.awt.BorderLayout.CENTER);

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseClicked
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jLabel8MouseClicked

    private void btnSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaActionPerformed
        jtfMK.setEnabled(true);
        jcbPQ.setEnabled(true);
        event = true ;
    }//GEN-LAST:event_btnSuaActionPerformed

    private void btnLuuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLuuActionPerformed
        if(event){
            if(!f.checkPassword(jtfMK.getText())){
               // JOptionPane.showMessageDialog(rootPane, "Mật khẩu không hợp lệ");
                lbMk.setText("Mật khẩu phải đủ 10 số, có chữ cái viết hoa và chữ cái đặc biệt!");
            }          
            else{
                lbMk.setText("");
                DTO_TaiKhoan tk = new DTO_TaiKhoan();
                tk.setMANV(jtfMANV.getText());
                tk.setTENDN(jtfTK.getText());
                tk.setMK(jtfMK.getText());
                if(jcbPQ.getSelectedItem().equals("Quản lý"))
                    tk.setPQ("ql");
                else 
                    tk.setPQ("nv");
                tk.setTRANGTHAI(1);
                if(tkbus.updateTaiKhoan(tk)){
                    JOptionPane.showMessageDialog(rootPane, "Thay đổi thành công!");
                    event = false;              
                    ql.setDateToTable();
                    this.dispose();
                }
                else
                    JOptionPane.showMessageDialog(rootPane, "Thay đổi thất bại !"); 
            }
        }
        else
            this.dispose();
        
    }//GEN-LAST:event_btnLuuActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLuu;
    private javax.swing.JButton btnSua;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JComboBox<String> jcbPQ;
    private javax.swing.JTextField jtfMANV;
    private javax.swing.JTextField jtfMK;
    private javax.swing.JTextField jtfTK;
    private keeptoo.KGradientPanel kGradientPanel1;
    private javax.swing.JLabel lbMk;
    // End of variables declaration//GEN-END:variables
}
