/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package GUI_QuanLy;

import DTO.DTO_NVTK;
import DTO.DTO_NhanVien;
import DTO.DTO_TaiKhoan;
import QLController.QuanLyThongKeController;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author Admin
 */
public class GUI_QuanLyThongKe extends javax.swing.JPanel {

    /**
     * Creates new form GUI_QuanLyThongKe
     */
    DTO_NhanVien nv ;
    DTO_TaiKhoan tk ;
    QuanLyThongKeController controller = new QuanLyThongKeController();
    public GUI_QuanLyThongKe(DTO_TaiKhoan tk ,DTO_NhanVien nv) {
        initComponents();
        this.tk = tk;
        this.nv = nv;
        setGiaoDien();
        
    }

    public void setGiaoDien(){
        if(tk.getPQ().equals("ql"))
        {
            jPanel8.setVisible(true);
            ListTK.setVisible(true);
            controller.setDataToChart2(TKview);
        }
        else if(tk.getPQ().equals("nv")){
            jPanel8.setVisible(false);
            ListTK.setVisible(false);
            controller.setDataToChartNv(TKview, nv.getMANV());
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ThongKE = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        ListTK = new javax.swing.JComboBox<>();
        jPanel2 = new javax.swing.JPanel();
        TKview = new javax.swing.JPanel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new java.awt.BorderLayout());

        ThongKE.setLayout(new java.awt.BorderLayout());

        jPanel8.setBackground(new java.awt.Color(17, 153, 142));
        jPanel8.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Chức năng", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14))); // NOI18N
        jPanel8.setPreferredSize(new java.awt.Dimension(230, 529));
        jPanel8.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 5, 15));

        ListTK.setFont(new java.awt.Font("Raavi", 0, 14)); // NOI18N
        ListTK.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "DoanhThu", "SPBC", "NVBC", "TongKet" }));
        ListTK.setPreferredSize(new java.awt.Dimension(150, 40));
        ListTK.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                ListTKItemStateChanged(evt);
            }
        });
        jPanel8.add(ListTK);

        ThongKE.add(jPanel8, java.awt.BorderLayout.LINE_END);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Thông kê", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14))); // NOI18N
        jPanel2.setLayout(new java.awt.BorderLayout());

        javax.swing.GroupLayout TKviewLayout = new javax.swing.GroupLayout(TKview);
        TKview.setLayout(TKviewLayout);
        TKviewLayout.setHorizontalGroup(
            TKviewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1010, Short.MAX_VALUE)
        );
        TKviewLayout.setVerticalGroup(
            TKviewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 765, Short.MAX_VALUE)
        );

        jPanel2.add(TKview, java.awt.BorderLayout.CENTER);

        ThongKE.add(jPanel2, java.awt.BorderLayout.CENTER);

        add(ThongKE, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void ListTKItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_ListTKItemStateChanged
        // TODO add your handling code here:
        if(ListTK.getSelectedItem().toString().equals("DoanhThu")){
          controller.setDataToChart2(TKview);
        }else if(ListTK.getSelectedItem().toString().equals("SPBC")){
          controller.setDataToChart1(TKview);         
        }else if(ListTK.getSelectedItem().toString().equals("NVBC")){
          controller.setDataToChart3(TKview);
        }else if(ListTK.getSelectedItem().toString().equals("TongKet")){
          tongKet(TKview);
        }
    }//GEN-LAST:event_ListTKItemStateChanged
    public void tongKet(JPanel jpnItem){
        GUI_TongDoanhThu tdt = new GUI_TongDoanhThu();
        jpnItem.removeAll();
        jpnItem.setLayout(new CardLayout());
        jpnItem.add(tdt);
        jpnItem.validate();
        jpnItem.repaint();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> ListTK;
    private javax.swing.JPanel TKview;
    private javax.swing.JPanel ThongKE;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel8;
    // End of variables declaration//GEN-END:variables
}
