/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package GUI_QuanLy;

import function.*;
import BUS.*;
import DTO.*;
import java.awt.Dimension;
import java.awt.Font;
import java.awt.event.MouseEvent;
import java.text.DecimalFormat;
import java.util.*;
import javax.swing.JLabel;
import javax.swing.JTable;
import javax.swing.RowFilter;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.JTableHeader;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author Admin
 */
public class GUI_QuanLyHoaDon extends javax.swing.JPanel {
    private TableRowSorter<TableModel> rowSorter ;
    public BUS_HoaDon hdBus = new BUS_HoaDon();
    public funcDungChung fuc = new funcDungChung();
    /**
     * Creates new form GUI_QuanLyHoaDon
     */
    public GUI_QuanLyHoaDon() {
        initComponents();
        loadHoaDonList(hdBus.getList());
        eventFind();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        QuanLyHoaDon = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jTextField1 = new javax.swing.JTextField();
        jPanel7 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_HoaDon = new javax.swing.JTable();

        setPreferredSize(new java.awt.Dimension(1250, 768));
        setLayout(new java.awt.BorderLayout());

        QuanLyHoaDon.setMinimumSize(new java.awt.Dimension(1250, 768));
        QuanLyHoaDon.setPreferredSize(new java.awt.Dimension(1250, 768));
        QuanLyHoaDon.setLayout(new java.awt.BorderLayout());

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));
        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Tìm kiếm", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14))); // NOI18N
        jPanel6.setPreferredSize(new java.awt.Dimension(1432, 70));
        jPanel6.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 10, 5));

        jTextField1.setPreferredSize(new java.awt.Dimension(250, 30));
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        jPanel6.add(jTextField1);

        QuanLyHoaDon.add(jPanel6, java.awt.BorderLayout.PAGE_START);

        jPanel7.setBackground(new java.awt.Color(17, 153, 142));
        jPanel7.setPreferredSize(new java.awt.Dimension(1432, 20));

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1250, Short.MAX_VALUE)
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );

        QuanLyHoaDon.add(jPanel7, java.awt.BorderLayout.PAGE_END);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Danh sách hóa đơn", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14))); // NOI18N

        tbl_HoaDon.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tbl_HoaDon.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "MÃ HĐ", "MÃ NV", "MÃ KH", "NGÀY LẬP", "TỔNG TIỀN", "GIẢM GIÁ", "TIỀN THANH TOÁN", "TIỀN KH", "TIỀN THÓI"
            }
        ));
        jScrollPane1.setViewportView(tbl_HoaDon);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1228, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 642, Short.MAX_VALUE)
                .addContainerGap())
        );

        QuanLyHoaDon.add(jPanel2, java.awt.BorderLayout.CENTER);

        add(QuanLyHoaDon, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jTextField1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel QuanLyHoaDon;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTable tbl_HoaDon;
    // End of variables declaration//GEN-END:variables
//FUCTION 
    // tùy chỉnh giao diện bảng 
    public void changeTable(JTable tbl_HoaDon){
        // Điều chỉnh chiều rộng của các cột tại đây
        //tbl_HoaDon.getColumnModel().getColumn(0).setPreferredWidth(200); // Ví dụ: Đặt chiều rộng của cột 0 là 100 pixels
        //tbl_HoaDon.getColumnModel().getColumn(1).setPreferredWidth(200); // Ví dụ: Đặt chiều rộng của cột 1 là 80 pixels
        // Thực hiện tương tự cho các cột còn lại
        // Điều chỉnh chiều cao của các dòng
       tbl_HoaDon.setRowHeight(40);

       // Điều chỉnh font và chiều rộng của tiêu đề
       JTableHeader header = tbl_HoaDon.getTableHeader();
       header.setFont(new Font("Tahoma", Font.BOLD, 14));
       header.setPreferredSize(new Dimension(50, 50));

       // Căn giữa tiêu đề theo chiều dọc
       DefaultTableCellRenderer centerRenderer = (DefaultTableCellRenderer) header.getDefaultRenderer();
       centerRenderer.setHorizontalAlignment(JLabel.CENTER);   
       
       rowSorter = new TableRowSorter<>(tbl_HoaDon.getModel());
       tbl_HoaDon.setRowSorter(rowSorter);
       tbl_HoaDon.validate();
       tbl_HoaDon.repaint();
    }
    // hàm tạo bảng 
    public void loadHoaDonList(List<DTO_HoaDon> hoadon) {
        DefaultTableModel dtm = new DefaultTableModel();
        dtm.addColumn("MÃ HĐ");
        dtm.addColumn("MÃ NV");
        dtm.addColumn("MÃ KH");
        dtm.addColumn("Ngày lập");
        dtm.addColumn("Tổng Tiền");
        dtm.addColumn("Giảm giá");
        dtm.addColumn("Tiền thanh toán");
        dtm.addColumn("Tiền khách");
        dtm.addColumn("Tiền thừa");
        dtm.addColumn("Ngày kết thúc bảo hành");
        tbl_HoaDon.setModel(dtm);
        
        List<DTO_HoaDon> arr = new ArrayList<>() ;
        //arr = empBUS.getAllEmployees();
        arr = hoadon;
        for (int i = 0; i < arr.size(); i++) {
            DTO_HoaDon em = arr.get(i);
            
            String maHd = em.getMaHD();
            String maNv = em.getMaNV();
            String maKh = em.getMaKH();
            Date ngayLap = em.getNgayLap();
            Double tongTien = em.getTongTien();
            Double giamGia = em.getGiamGia();
            Double tienThanhToan = em.getTienThanhToan();
            Double tienKhach = em.getTienKhach();
            Double tienThua = em.getTienThoi();
            Date ngayKtBh = em.getNgayKtBh();
            
            Object[] row = {maHd, maNv, maKh, ngayLap, fuc.doubleToFormattedString(tongTien), fuc.doubleToFormattedString(giamGia), 
                fuc.doubleToFormattedString(tienThanhToan), fuc.doubleToFormattedString(tienKhach), 
                fuc.doubleToFormattedString(tienThua), ngayKtBh };
            dtm.addRow(row);
        }
        changeTable(tbl_HoaDon);
        
    
    }
    
    public void eventFind(){
        jTextField1.getDocument().addDocumentListener(new DocumentListener() {
            @Override
            public void insertUpdate(DocumentEvent e) {
                String text = jTextField1.getText();
                if(text.trim().length() == 0){
                    rowSorter.setRowFilter(null);
                }else{
                    rowSorter.setRowFilter(RowFilter.regexFilter("(?i)" + text));
                }
            }

            @Override
            public void removeUpdate(DocumentEvent e) {
                String text = jTextField1.getText();
                if(text.trim().length() == 0){
                    rowSorter.setRowFilter(null);
                }else{
                    rowSorter.setRowFilter(RowFilter.regexFilter("(?i)" + text));
                }
            }

            @Override
            public void changedUpdate(DocumentEvent e) {
                
            }
        });
    }

}
