/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package GUI_QuanLy;

import BUS.*;
import DTO.*;
import QLController.*;
import com.lowagie.text.Document;
import com.lowagie.text.DocumentException;
import com.lowagie.text.Element;
import com.lowagie.text.Font;
import com.lowagie.text.FontFactory;
import com.lowagie.text.PageSize;
import com.lowagie.text.Paragraph;
import com.lowagie.text.pdf.BaseFont;
import com.lowagie.text.pdf.PdfPTable;
import com.lowagie.text.pdf.PdfWriter;
import function.funcDungChung;
import java.awt.Dimension;
import java.awt.event.KeyEvent;
import java.awt.event.KeyListener;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.regex.Pattern;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JTextField;
import javax.swing.SwingUtilities;
import javax.swing.filechooser.FileNameExtensionFilter;


public class GUI_TrangChuBanHang extends javax.swing.JPanel {

    /**
     * Creates new form GUI_TrangChuBanHang
     */

    public QuanLySanPhamControllerfix qlf ;
    public DTO_SanPham sp = new DTO_SanPham();
    public BUS_SanPham spBus = new BUS_SanPham();
    public BUS_HoaDon hdbus=new BUS_HoaDon();
    public BUS_CTHD cthdbus=new BUS_CTHD();
    public BUS_KhachHang khbus=new BUS_KhachHang();
    public ArrayList<GUI_ContainerPhone> containers = new ArrayList<>();
    public double tt=0,tg=0,t=0,tienthua=0,tienkhach=0;
    private funcDungChung fuc = new funcDungChung();
    private QuanLyDSBH controller;
    public ArrayList<String> listsl = new ArrayList<>();
    public ArrayList<String> listtg = new ArrayList<>();
    public ArrayList<DTO_KhachHang> listkh = new ArrayList<>();
    List<DTO_SanPham> listItem= new ArrayList<>();
    GUI_GiaoDienChinh gd;
    public GUI_TrangChuBanHang(GUI_GiaoDienChinh gd) {
       initComponents();   
       controller=new QuanLyDSBH(jpnView, this,btnXoa,containers, this.jPanelSPs);
       controller.setDateToTable(null, 0,0);
       controller.setEvent();
       this.gd=gd;
       qlf = new QuanLySanPhamControllerfix((ArrayList<DTO_SanPham>) spBus.getList(), containers, this.jPanelSPs,this,this.controller);
       
    }

    public void load(){
        qlf.showSp(spBus.getList(), containers, this.jPanelSPs,controller);     
    }
    

    public void setTinhTien(double jtfTienGiam,double jtfTongTien,int sl) {//cap nhap lai tien khi tang so luong 1 sp hoac khi them 1 sp moi
        tt=tt+jtfTongTien*sl;
        tg=tg+jtfTienGiam*sl;
        
        this.jtfTienGiam.setText(fuc.doubleToFormattedString(tg)+" VNĐ");
        
        this.jtfTongTien.setText(fuc.doubleToFormattedString(tt)+" VNĐ");
        
        t=tt-tg;
        this.jtfThanhTien.setText(fuc.doubleToFormattedString(t)+" VNĐ");
    }
    public void setUpdate(double jtfTienGiam,double jtfTongTien,int sl){ //cap nhap lai tien khi giam so luong 1 sp hoac khi xoa 1 sp
        
        tt=tt-jtfTongTien*sl;
        tg=tg-jtfTienGiam*sl;
        
        this.jtfTienGiam.setText(fuc.doubleToFormattedString(tg)+" VNĐ");
        
        this.jtfTongTien.setText(fuc.doubleToFormattedString(tt)+" VNĐ");
        
        t=tt-tg;
        this.jtfThanhTien.setText(fuc.doubleToFormattedString(t)+" VNĐ");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jPanel15 = new javax.swing.JPanel();
        jPanel16 = new javax.swing.JPanel();
        jTextField1 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanelSPs = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jpnView = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        jPanel12 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jtfSdt = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jtfHotenKH = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jtfTongTien = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jtfTienGiam = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jtfThanhTien = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jtfTienKhachDua = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jtfTienThua = new javax.swing.JTextField();
        jPanel14 = new javax.swing.JPanel();
        btnXoa = new javax.swing.JButton();
        btnThanhToan = new javax.swing.JButton();
        jPanel10 = new javax.swing.JPanel();
        jPanel11 = new javax.swing.JPanel();

        setBackground(new java.awt.Color(255, 255, 255));
        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(17, 153, 142)));
        setPreferredSize(new java.awt.Dimension(1250, 789));
        setLayout(new java.awt.BorderLayout());

        jPanel1.setLayout(new java.awt.BorderLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new java.awt.BorderLayout());

        jPanel3.setLayout(new java.awt.BorderLayout());

        jPanel15.setBackground(new java.awt.Color(255, 255, 255));
        jPanel15.setOpaque(false);
        jPanel15.setPreferredSize(new java.awt.Dimension(850, 110));
        jPanel15.setLayout(new java.awt.BorderLayout());

        jPanel16.setBackground(new java.awt.Color(255, 255, 255));

        jTextField1.setPreferredSize(new java.awt.Dimension(250, 30));
        jTextField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField1KeyReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanel16Layout = new javax.swing.GroupLayout(jPanel16);
        jPanel16.setLayout(jPanel16Layout);
        jPanel16Layout.setHorizontalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel16Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(571, Short.MAX_VALUE))
        );
        jPanel16Layout.setVerticalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel16Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(47, Short.MAX_VALUE))
        );

        jPanel15.add(jPanel16, java.awt.BorderLayout.CENTER);

        jPanel3.add(jPanel15, java.awt.BorderLayout.PAGE_START);

        jScrollPane1.setToolTipText("");
        jScrollPane1.setPreferredSize(new java.awt.Dimension(850, 6000));

        jPanelSPs.setBackground(new java.awt.Color(255, 255, 255));
        java.awt.FlowLayout flowLayout1 = new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 20, 15);
        flowLayout1.setAlignOnBaseline(true);
        jPanelSPs.setLayout(flowLayout1);
        jScrollPane1.setViewportView(jPanelSPs);

        jPanel3.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        jPanel2.add(jPanel3, java.awt.BorderLayout.CENTER);

        jPanel1.add(jPanel2, java.awt.BorderLayout.CENTER);

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setPreferredSize(new java.awt.Dimension(400, 789));
        jPanel5.setLayout(new java.awt.BorderLayout());

        jPanel6.setPreferredSize(new java.awt.Dimension(400, 789));
        jPanel6.setLayout(new java.awt.BorderLayout());

        jPanel7.setLayout(new java.awt.BorderLayout());

        javax.swing.GroupLayout jpnViewLayout = new javax.swing.GroupLayout(jpnView);
        jpnView.setLayout(jpnViewLayout);
        jpnViewLayout.setHorizontalGroup(
            jpnViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 380, Short.MAX_VALUE)
        );
        jpnViewLayout.setVerticalGroup(
            jpnViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 377, Short.MAX_VALUE)
        );

        jPanel7.add(jpnView, java.awt.BorderLayout.CENTER);

        jPanel6.add(jPanel7, java.awt.BorderLayout.CENTER);

        jPanel8.setBackground(new java.awt.Color(17, 153, 142));
        jPanel8.setPreferredSize(new java.awt.Dimension(400, 110));
        jPanel8.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 5, 30));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("DANH SÁCH CHỌN");
        jPanel8.add(jLabel2);

        jPanel6.add(jPanel8, java.awt.BorderLayout.PAGE_START);

        jPanel9.setBackground(new java.awt.Color(17, 153, 142));
        jPanel9.setPreferredSize(new java.awt.Dimension(400, 370));
        jPanel9.setLayout(new java.awt.BorderLayout());

        jPanel12.setOpaque(false);
        jPanel12.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel4.setOpaque(false);
        jPanel4.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 10, 10));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Số điện thoại:");
        jLabel1.setPreferredSize(new java.awt.Dimension(150, 30));
        jPanel4.add(jLabel1);

        jtfSdt.setPreferredSize(new java.awt.Dimension(200, 30));
        jtfSdt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtfSdtKeyReleased(evt);
            }
        });
        jPanel4.add(jtfSdt);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Họ Tên khách hàng:");
        jLabel3.setPreferredSize(new java.awt.Dimension(150, 30));
        jPanel4.add(jLabel3);

        jtfHotenKH.setPreferredSize(new java.awt.Dimension(200, 30));
        jPanel4.add(jtfHotenKH);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Tổng tiền:");
        jLabel4.setPreferredSize(new java.awt.Dimension(150, 30));
        jPanel4.add(jLabel4);

        jtfTongTien.setText("0");
        jtfTongTien.setEnabled(false);
        jtfTongTien.setPreferredSize(new java.awt.Dimension(200, 30));
        jPanel4.add(jtfTongTien);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Số tiền được giảm:");
        jLabel5.setPreferredSize(new java.awt.Dimension(150, 30));
        jPanel4.add(jLabel5);

        jtfTienGiam.setText("0");
        jtfTienGiam.setEnabled(false);
        jtfTienGiam.setPreferredSize(new java.awt.Dimension(200, 30));
        jPanel4.add(jtfTienGiam);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Thành tiền:");
        jLabel6.setPreferredSize(new java.awt.Dimension(150, 30));
        jPanel4.add(jLabel6);

        jtfThanhTien.setText("0");
        jtfThanhTien.setEnabled(false);
        jtfThanhTien.setPreferredSize(new java.awt.Dimension(200, 30));
        jPanel4.add(jtfThanhTien);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Tiền khách trả:");
        jLabel7.setPreferredSize(new java.awt.Dimension(150, 30));
        jPanel4.add(jLabel7);

        jtfTienKhachDua.setText("0");
        jtfTienKhachDua.setPreferredSize(new java.awt.Dimension(200, 30));
        jtfTienKhachDua.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtfTienKhachDuaKeyReleased(evt);
            }
        });
        jPanel4.add(jtfTienKhachDua);

        jPanel12.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 10, 370, 250));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Tiền Thừa:");
        jLabel8.setPreferredSize(new java.awt.Dimension(150, 30));
        jPanel12.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 260, -1, -1));

        jtfTienThua.setEnabled(false);
        jtfTienThua.setPreferredSize(new java.awt.Dimension(200, 30));
        jtfTienThua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfTienThuaActionPerformed(evt);
            }
        });
        jPanel12.add(jtfTienThua, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 260, -1, -1));

        jPanel9.add(jPanel12, java.awt.BorderLayout.CENTER);

        jPanel14.setBackground(new java.awt.Color(17, 153, 142));
        jPanel14.setPreferredSize(new java.awt.Dimension(400, 80));
        jPanel14.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 15, 5));

        btnXoa.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnXoa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/cartdelete.png"))); // NOI18N
        btnXoa.setText("XÓA SP");
        btnXoa.setPreferredSize(new java.awt.Dimension(170, 50));
        jPanel14.add(btnXoa);

        btnThanhToan.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnThanhToan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/billTichXanh.png"))); // NOI18N
        btnThanhToan.setText("THANH TOÁN");
        btnThanhToan.setPreferredSize(new java.awt.Dimension(170, 50));
        btnThanhToan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThanhToanActionPerformed(evt);
            }
        });
        jPanel14.add(btnThanhToan);

        jPanel9.add(jPanel14, java.awt.BorderLayout.PAGE_END);

        jPanel6.add(jPanel9, java.awt.BorderLayout.PAGE_END);

        jPanel10.setBackground(new java.awt.Color(17, 153, 142));
        jPanel10.setPreferredSize(new java.awt.Dimension(10, 589));

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jPanel6.add(jPanel10, java.awt.BorderLayout.LINE_END);

        jPanel11.setBackground(new java.awt.Color(17, 153, 142));
        jPanel11.setPreferredSize(new java.awt.Dimension(10, 589));

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jPanel6.add(jPanel11, java.awt.BorderLayout.LINE_START);

        jPanel5.add(jPanel6, java.awt.BorderLayout.LINE_END);

        jPanel1.add(jPanel5, java.awt.BorderLayout.LINE_END);

        add(jPanel1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents
public void showthongbao(){
    JOptionPane.showMessageDialog(null, "Hãy chọn sản phẩm cần xóa", "Thông báo", JOptionPane.WARNING_MESSAGE);
}
    private void jTextField1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField1KeyReleased
        String key = jTextField1.getText().toString().trim();
        if(!key.isEmpty()){
          qlf = new QuanLySanPhamControllerfix((ArrayList<DTO_SanPham>) spBus.timSpDaKhoa(key), containers, this.jPanelSPs,this,this.controller);    
        }
        else     
         qlf = new QuanLySanPhamControllerfix((ArrayList<DTO_SanPham>) spBus.getList(), containers, this.jPanelSPs,this,this.controller);
    }//GEN-LAST:event_jTextField1KeyReleased

    private void jtfTienThuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfTienThuaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfTienThuaActionPerformed

    private void btnThanhToanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThanhToanActionPerformed
        listItem=controller.getListItem();
        listsl=controller.getListsl();
        listtg=controller.getListtg();
        if(tt==0)
                    JOptionPane.showMessageDialog(null, "Hãy chọn sản phẩm", "Thông báo", JOptionPane.WARNING_MESSAGE);
        
        else
            if(check_NumberPhone(jtfSdt.getText())==false)
                JOptionPane.showMessageDialog(null, "Số điện thoại khách hàng không hợp lệ", "Thông báo", JOptionPane.WARNING_MESSAGE);
        else
            if(jtfHotenKH.getText().equals(""))
            JOptionPane.showMessageDialog(null, "Thông tin khách hàng chưa đầy đủ", "Thông báo", JOptionPane.WARNING_MESSAGE);    
        else
                if(jtfTienThua.getText().equals(""))
                    JOptionPane.showMessageDialog(null, "Tiền khách đưa không hợp lệ", "Thông báo", JOptionPane.WARNING_MESSAGE);
        else{
        JFileChooser fileChooser = new JFileChooser();
        FileNameExtensionFilter filter = new FileNameExtensionFilter("File PDF", "pdf");
        fileChooser.setFileFilter(filter);

        int returnValue = fileChooser.showSaveDialog(null);
        if (returnValue == JFileChooser.APPROVE_OPTION) {
            String filePath = fileChooser.getSelectedFile().getAbsolutePath();

            // Đảm bảo đuôi file .pdf
            if (!filePath.endsWith(".pdf")) {
                filePath += ".pdf";
            }
             
             Document doc=new Document(PageSize.A4, 20, 20, 20, 20);
             try {
                 PdfWriter.getInstance(doc, new FileOutputStream(filePath));
                 
                 doc.open();
                // Tạo đối tượng Font cho chữ in đậm
                Font boldFont = FontFactory.getFont(FontFactory.HELVETICA_BOLD, 24);
                Font font = FontFactory.getFont(FontFactory.HELVETICA_BOLD, 12);
                // Tạo đối tượng Paragraph với văn bản "HOA DON MUA HANG" và định dạng chữ in đậm
                BaseFont unicodeFont = BaseFont.createFont("\\Font\\ARIALUNI.TTF", BaseFont.IDENTITY_H, BaseFont.EMBEDDED);
                int fontSize = 12;
                Paragraph centerText = new Paragraph("CỬA HÀNG BÁN ĐIỆN THOẠI HASOLIFE", new Font(unicodeFont, fontSize));
                centerText.setAlignment(Element.ALIGN_CENTER);

                // Thêm đối tượng Paragraph vào tài liệu
                 doc.add(centerText);
                 doc.add(new Paragraph("\n"));
                 doc.add(new Paragraph("Đia Chỉ: 273 An Dương Vương, Phường 3, Quận 5, TPHCM",new Font(unicodeFont, fontSize)));
                 doc.add(new Paragraph("Liên hệ: 028 3835 4409",new Font(unicodeFont, fontSize)));
                 doc.add(new Paragraph("Tên khách hàng: "+ jtfHotenKH.getText()+"                                 "+" Số điện thoại: "+jtfSdt.getText(),new Font(unicodeFont, fontSize)));
                 SimpleDateFormat dateFormat = new SimpleDateFormat("dd/MM/yyyy");
                 Date d= new Date(System.currentTimeMillis());
                 Calendar calendar = Calendar.getInstance();
                calendar.setTime(d);
                calendar.add(Calendar.MONTH, 3);
                Date futureDate = calendar.getTime();
                 doc.add(new Paragraph("Ngày lập: "+dateFormat.format(d)+"                   "+"Ngày kết thúc bảo hành: "+
                         dateFormat.format(futureDate),new Font(unicodeFont, fontSize)));
                 doc.add(new Paragraph("\n"));
                 float[] columnWidths = {1.5f, 2.5f, 1.5f, 1.5f};
                 PdfPTable b1 = new PdfPTable(columnWidths);
                 b1.addCell(new Paragraph("Mã Sản Phẩm",new Font(unicodeFont, fontSize)));
                  b1.addCell(new Paragraph("Tên Sản Phẩm",new Font(unicodeFont, fontSize)));
                   b1.addCell(new Paragraph("Đơn giá",new Font(unicodeFont, fontSize)));
                    b1.addCell(new Paragraph("Số lượng",new Font(unicodeFont, fontSize)));
                 for (int i = 0; i < controller.getTable().getRowCount(); i++) {
                     String masp=controller.getTable().getValueAt(i, 0).toString();
                     String tensp=controller.getTable().getValueAt(i, 1).toString();
                     String dongia= controller.getTable().getValueAt(i, 2).toString();
                     String sl=controller.getTable().getValueAt(i, 3).toString();
                     
                     b1.addCell(masp);
                     b1.addCell(tensp);
                     b1.addCell(dongia);
                     b1.addCell(sl);
                     
            
                 }
                 doc.add(b1);
                 doc.add(new Paragraph("\n"));
                doc.add(new Paragraph("Tổng tiền: "+jtfTongTien.getText()+"                                       "+"Giảm giá: "+jtfTienGiam.getText()
                         ,new Font(unicodeFont, fontSize))); 
                doc.add(new Paragraph("Tiền Thanh toán: " +jtfThanhTien.getText()+"                               "+ ""+"Tiền khách: "+fuc.doubleToFormattedString(tienkhach)+" VNĐ",new Font(unicodeFont, fontSize))); 
                 doc.add(new Paragraph("Tiền thối: " +jtfTienThua.getText(),new Font(unicodeFont, fontSize))); 
             } catch (FileNotFoundException ex) {
                 Logger.getLogger(GUI_ThongTinBaoHanh.class.getName()).log(Level.SEVERE, null, ex);
                 JOptionPane.showMessageDialog(null, "Xuất thất bại", "Thông báo", JOptionPane.WARNING_MESSAGE);
             } catch (DocumentException ex) {
                 Logger.getLogger(GUI_ThongTinBaoHanh.class.getName()).log(Level.SEVERE, null, ex);
                 JOptionPane.showMessageDialog(null, "Xuất thất bại", "Thông báo", JOptionPane.WARNING_MESSAGE);
             }  catch (IOException ex) {
                    Logger.getLogger(GUI_ThongTinBaoHanh.class.getName()).log(Level.SEVERE, null, ex);
                }
           doc.close();
           DTO_HoaDon hd=new DTO_HoaDon();
           int t =hdbus.getList().size()+1;
          
            if(t<10)
                hd.setMaHD("HD0"+t);
            else
                hd.setMaHD("HD"+t);
            DTO_KhachHang kh=new DTO_KhachHang();
            listkh=khbus.timnv(jtfSdt.getText());
            if(listkh.size()==0)
            { int k =khbus.getList().size()+1;
                
                 if(k<10)
                     kh.setMAKH("KH0"+k);
                 else
                     kh.setMAKH("KH"+k);
                 kh.setSDTKH(jtfSdt.getText());
                 kh.setTENKH(jtfHotenKH.getText());
                 kh.setTRANGTHAI(1);
                 khbus.addKhachHang(kh);
                 hd.setMaKH(kh.getMAKH());
                 
            }
            else
                hd.setMaKH(listkh.get(0).getMAKH());
                
            
            hd.setMaNV("NV001");
            Date d= new Date(System.currentTimeMillis());
            hd.setNgayLap(d);
            Calendar calendar = Calendar.getInstance();
            calendar.setTime(d);
            calendar.add(Calendar.MONTH, 3);
            Date futureDate = calendar.getTime();
            hd.setNgayKtBh(futureDate);
            //
            hd.setTienKhach(tienkhach);
            hd.setTienThanhToan(this.t);
            hd.setTienThoi(tienthua);
            hd.setTongTien(tt);
            hd.setTrangThai(1);
            hd.setGiamGia(tg);
            hdbus.addHoaDon(hd);
            for(int i=0;i<listItem.size();i++)
            {
            DTO_CTHD cthd=new DTO_CTHD();
            cthd.setMaHD(hd.getMaHD());
            cthd.setMaSp(listItem.get(i).getMaSp());
            cthd.setSoLuong(Integer.parseInt(listsl.get(i)));
            cthd.setTenSp(listItem.get(i).getTenSp());
            cthd.setThanhTien(listItem.get(i).getDonGia()*Integer.parseInt(listsl.get(i)));
            cthd.setDonGia(listItem.get(i).getDonGia());
            cthdbus.addCTHD(cthd);
                    }
            for(int i=0;i<listItem.size();i++)
            {
                spBus.updateSanPham(listItem.get(i));
            }
            listItem.clear();
            listsl.clear();
            listtg.clear();
            controller.getListslbd().clear();
            controller.setListItem(listItem);
            controller.setListsl(listsl);
            controller.setListslbd(controller.getListslbd());
            controller.setListtg(listtg);
            controller.setDateToTable(null, 0, 0);
            tt=0;
            tg=0;
            this.t=0;
            tienthua=0;
            jtfTienKhachDua.setText("");
            jtfSdt.setText("");
            jtfHotenKH.setText("");
            jtfThanhTien.setText("0");
            jtfTienGiam.setText("0");
            jtfTienThua.setText("");
            jtfTongTien.setText("0");
            
            this.load();
            gd.getPanelSPvaKM().getGuiSanPham().getQlf().setDateToTable();
            
            
            
            
            
                
            
        }   
        }
        
        
    }//GEN-LAST:event_btnThanhToanActionPerformed
public boolean check_NumberPhone(String str) {
      Pattern p_Viettel=Pattern.compile("^03[2-9][0-9]{8}$");
      Pattern p_Mobifone=Pattern.compile("^07(0|9|7|6|8)[0-9]{7}$");
      Pattern p_Vinaphone=Pattern.compile("^08[1-5][0-9]{7}$");
      Pattern p_Vietnamobile=Pattern.compile("^05(6|8)[0-9]{7}$");
      Pattern p_Gmobile=Pattern.compile("^059[0-9]{7}$");
        
        
        if(str.length()==10 && str.indexOf("0")==0 )
        {
            return true;
            
        }else
        {
            return false;
        }
    }
    private void jtfSdtKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfSdtKeyReleased
       ArrayList<DTO_KhachHang> listkh=khbus.getList();
            for (DTO_KhachHang x: listkh){
                if(x.getSDTKH().equals(jtfSdt.getText()))
                {jtfHotenKH.setText(x.getTENKH());
                jtfHotenKH.setEnabled(false);
                break;
                }
                else
                {jtfHotenKH.setText("");
                jtfHotenKH.setEnabled(true);}
                    
                
            }
    }//GEN-LAST:event_jtfSdtKeyReleased

    private void jtfTienKhachDuaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfTienKhachDuaKeyReleased
      if(!jtfTienKhachDua.getText().equals("") && jtfTienKhachDua.getText().matches("\\d+")==true)
      { tienkhach=Double.parseDouble(jtfTienKhachDua.getText());
      if(tienkhach>=t)
      {
       jtfTienThua.setText(fuc.doubleToFormattedString(tienkhach-t)+" VNĐ");
       tienthua=tienkhach-t;
      }
      else
      {jtfTienThua.setText("");
      tienthua=0;}
      }
      else
      {jtfTienThua.setText("");
      tienthua=0;}
    }//GEN-LAST:event_jtfTienKhachDuaKeyReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnThanhToan;
    private javax.swing.JButton btnXoa;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JPanel jPanelSPs;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JTextField jTextField1;
    private javax.swing.JPanel jpnView;
    private javax.swing.JTextField jtfHotenKH;
    private javax.swing.JTextField jtfSdt;
    private javax.swing.JTextField jtfThanhTien;
    private javax.swing.JTextField jtfTienGiam;
    private javax.swing.JTextField jtfTienKhachDua;
    private javax.swing.JTextField jtfTienThua;
    private javax.swing.JTextField jtfTongTien;
    // End of variables declaration//GEN-END:variables

}
