/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package GUI_QuanLy;


import BUS.BUS_HoaDon;
import BUS.BUS_KhachHang;
import BUS.BUS_NhanVien;
import BUS.BUS_PhieuNhap;
import BUS.BUS_SanPham;
import DTO.DTO_HoaDon;
import DTO.DTO_KhachHang;
import DTO.DTO_NVTK;
import DTO.DTO_NhanVien;
import DTO.DTO_PhieuNhap;
import function.funcDungChung;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.LayoutManager;
import java.awt.RenderingHints;
import javax.swing.JPanel;

/**
 *
 * @author Admin
 */
public class GUI_TongDoanhThu extends javax.swing.JPanel {

    /**
     * Creates new form GUI_TongDoanhThu
     */
    private funcDungChung fuc = new funcDungChung();
    private BUS_HoaDon hdbus = new BUS_HoaDon();
    private BUS_KhachHang khBus = new BUS_KhachHang();
    private BUS_NhanVien nvBus = new BUS_NhanVien();
    private BUS_PhieuNhap pnBus = new BUS_PhieuNhap();
    private BUS_SanPham spBus = new BUS_SanPham();
//    private String tongTienThuDuoc = "";
//    private String tongTienGiamGia = "";
//    private String tongTienNhap = "";
//    private String tongTienLoi = "";
//    private int soNv,soKh;
    
    public GUI_TongDoanhThu() {
        initComponents();
        tongketDoanhThu();
    }
    public void tongketDoanhThu(){
        Double tongTienThuDuoc = 0.0 ;
        Double tongTienGiamGia = 0.0 ;
        Double tongTienNhap = 0.0; 
        Double tongTienLoi = 0.0;
        int soNv = 0;
        int soKh = 0;
        for(DTO_HoaDon hd:hdbus.getList()){
           tongTienThuDuoc += hd.getTienThanhToan();
           tongTienGiamGia += hd.getGiamGia();
        }
        for(DTO_PhieuNhap pn : pnBus.getList()){
            tongTienNhap += pn.getTONGTIEN();
        }
        for(DTO_NhanVien nv: nvBus.getList()){
            soNv++;
        }
        for(DTO_KhachHang kh: khBus.getList()){
            soKh++;
        }
        
        tongTienLoi = tongTienThuDuoc - tongTienNhap ;
        //if(tongTienLoi>=0){
            jtfTienLoi.setText(fuc.doubleToFormattedString(tongTienLoi));
       // }
        jlTongTienNhap.setText(fuc.doubleToFormattedString(tongTienNhap));
        jlTongTinThuDuoc.setText(fuc.doubleToFormattedString(tongTienThuDuoc));
        jltienGiamGia.setText(fuc.doubleToFormattedString(tongTienGiamGia));
        jlTongSoKh.setText(soKh+"");
        jlTongSoNv.setText(soNv+"");
        
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new RoundedPanel(100, Color.WHITE);
        jLabel1 = new javax.swing.JLabel();
        jlTongTinThuDuoc = new javax.swing.JLabel();
        jPanel4 = new RoundedPanel(100, Color.WHITE);
        jLabel3 = new javax.swing.JLabel();
        jltienGiamGia = new javax.swing.JLabel();
        jPanel5 = new RoundedPanel(100, Color.WHITE);
        jLabel5 = new javax.swing.JLabel();
        jlTongSoKh = new javax.swing.JLabel();
        jPanel6 = new RoundedPanel(100, Color.WHITE);
        jLabel7 = new javax.swing.JLabel();
        jlTongSoNv = new javax.swing.JLabel();
        jPanel7 = new RoundedPanel(100, Color.WHITE);
        jLabel9 = new javax.swing.JLabel();
        jlTongTienNhap = new javax.swing.JLabel();
        jPanel8 = new RoundedPanel(100, Color.WHITE);
        jLabel11 = new javax.swing.JLabel();
        jtfTienLoi = new javax.swing.JLabel();

        setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 20, 40));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setOpaque(false);
        jPanel3.setPreferredSize(new java.awt.Dimension(300, 300));
        jPanel3.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 5, 30));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("TỔNG TIỀN THU ĐƯỢC:");
        jPanel3.add(jLabel1);

        jlTongTinThuDuoc.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jlTongTinThuDuoc.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlTongTinThuDuoc.setText("0");
        jlTongTinThuDuoc.setPreferredSize(new java.awt.Dimension(270, 29));
        jPanel3.add(jlTongTinThuDuoc);

        add(jPanel3);

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setOpaque(false);
        jPanel4.setPreferredSize(new java.awt.Dimension(300, 300));
        jPanel4.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 5, 30));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel3.setText("TỔNG TIỀN GIẢM GIÁ");
        jPanel4.add(jLabel3);

        jltienGiamGia.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jltienGiamGia.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jltienGiamGia.setText("0");
        jltienGiamGia.setPreferredSize(new java.awt.Dimension(270, 29));
        jPanel4.add(jltienGiamGia);

        add(jPanel4);

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setOpaque(false);
        jPanel5.setPreferredSize(new java.awt.Dimension(300, 300));
        jPanel5.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 5, 30));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("TỔNG SỐ KHÁCH HÀNG:");
        jLabel5.setPreferredSize(new java.awt.Dimension(270, 29));
        jPanel5.add(jLabel5);

        jlTongSoKh.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jlTongSoKh.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlTongSoKh.setText("0");
        jlTongSoKh.setPreferredSize(new java.awt.Dimension(200, 29));
        jPanel5.add(jlTongSoKh);

        add(jPanel5);

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));
        jPanel6.setOpaque(false);
        jPanel6.setPreferredSize(new java.awt.Dimension(300, 300));
        jPanel6.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 5, 30));

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("TỔNG SỐ NHÂN VIÊN:");
        jLabel7.setPreferredSize(new java.awt.Dimension(270, 29));
        jPanel6.add(jLabel7);

        jlTongSoNv.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jlTongSoNv.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlTongSoNv.setText("0");
        jlTongSoNv.setPreferredSize(new java.awt.Dimension(200, 29));
        jPanel6.add(jlTongSoNv);

        add(jPanel6);

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));
        jPanel7.setMaximumSize(new java.awt.Dimension(300, 300));
        jPanel7.setMinimumSize(new java.awt.Dimension(300, 300));
        jPanel7.setOpaque(false);
        jPanel7.setPreferredSize(new java.awt.Dimension(300, 300));
        jPanel7.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 5, 30));

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel9.setText("TỔNG SỐ TIỀN NHẬP:");
        jPanel7.add(jLabel9);

        jlTongTienNhap.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jlTongTienNhap.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlTongTienNhap.setText("0");
        jlTongTienNhap.setPreferredSize(new java.awt.Dimension(270, 29));
        jPanel7.add(jlTongTienNhap);

        add(jPanel7);

        jPanel8.setBackground(new java.awt.Color(255, 255, 255));
        jPanel8.setMaximumSize(new java.awt.Dimension(300, 300));
        jPanel8.setMinimumSize(new java.awt.Dimension(300, 300));
        jPanel8.setOpaque(false);
        jPanel8.setPreferredSize(new java.awt.Dimension(300, 300));
        jPanel8.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 5, 30));

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel11.setText("TỔNG TIỀN LỜI:");
        jLabel11.setPreferredSize(new java.awt.Dimension(250, 29));
        jPanel8.add(jLabel11);

        jtfTienLoi.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jtfTienLoi.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jtfTienLoi.setText("0");
        jtfTienLoi.setPreferredSize(new java.awt.Dimension(250, 29));
        jPanel8.add(jtfTienLoi);

        add(jPanel8);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JLabel jlTongSoKh;
    private javax.swing.JLabel jlTongSoNv;
    private javax.swing.JLabel jlTongTienNhap;
    private javax.swing.JLabel jlTongTinThuDuoc;
    private javax.swing.JLabel jltienGiamGia;
    private javax.swing.JLabel jtfTienLoi;
    // End of variables declaration//GEN-END:variables
class RoundedPanel extends JPanel
    {
        private Color backgroundColor;
        private int cornerRadius = 15;
        public RoundedPanel(LayoutManager layout, int radius) {
            super(layout);
            cornerRadius = radius;
        }
        public RoundedPanel(LayoutManager layout, int radius, Color bgColor) {
            super(layout);
            cornerRadius = radius;
            backgroundColor = bgColor;
        }
        public RoundedPanel(int radius) {
            super();
            cornerRadius = radius;
            
        }
        public RoundedPanel(int radius, Color bgColor) {
            super();
            cornerRadius = radius;
            backgroundColor = bgColor;
        }
        @Override
        protected void paintComponent(Graphics g) {
            super.paintComponent(g);
            Dimension arcs = new Dimension(cornerRadius, cornerRadius);
            int width = getWidth();
            int height = getHeight();
            Graphics2D graphics = (Graphics2D) g;
            graphics.setRenderingHint(RenderingHints.KEY_ANTIALIASING, RenderingHints.VALUE_ANTIALIAS_ON);
            //Draws the rounded panel with borders.
            if (backgroundColor != null) {
                graphics.setColor(backgroundColor);
            } else {
                graphics.setColor(getBackground());
            }
            graphics.fillRoundRect(0, 0, width-1, height-1, arcs.width, arcs.height); //paint background
            graphics.setColor(getForeground());
//            graphics.drawRoundRect(0, 0, width-1, height-1, arcs.width, arcs.height); //paint border
//             
        }
    }
}
